# Generated by Django 4.2.5 on 2023-09-26 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('href', models.CharField(default='', max_length=500, primary_key=True, serialize=False,
                                          verbose_name='详情页')),
                ('name', models.CharField(default='', max_length=255, verbose_name='职位')),
                ('salaryMin',
                 models.DecimalField(default=0.00, max_digits=10, decimal_places=2, verbose_name='薪资下限')),
                ('salaryMax',
                 models.DecimalField(default=0.00, max_digits=10, decimal_places=2, verbose_name='薪资上限')),
                ('salaryBonus', models.IntegerField(default=0, verbose_name='年终奖')),
                ('city', models.CharField(default='', max_length=255, verbose_name='城市', db_column='location')),
                ('exp', models.CharField(default='', max_length=255, verbose_name='经验', db_column='experience')),
                ('edu', models.CharField(default='', max_length=255, verbose_name='学历', db_column='education')),
                ('jobType', models.CharField(default='', max_length=255, verbose_name='职位类型')),
                ('num', models.IntegerField(default='', verbose_name='招聘人数')),
                ('tags', models.CharField(default='', max_length=255, verbose_name='标签', db_column='tagList')),
                ('content', models.TextField(default='', verbose_name='职位描述')),
                ('com', models.CharField(default='', max_length=255, verbose_name='公司', db_column='company')),
                ('comSize',
                 models.CharField(default='', max_length=255, verbose_name='公司规模', db_column='companySize')),
                ('comTag',
                 models.CharField(default='', max_length=255, verbose_name='公司类型', db_column='companyTag')),
                ('staff', models.CharField(default='', max_length=255, verbose_name='经理')),
                ('keyList', models.TextField(default='', verbose_name='关键词')),
                ('delete', models.IntegerField(default=0, verbose_name='是否删除', db_column='deleteStatus'))
            ],
        ),
        migrations.CreateModel(
            name='joblist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(default='', max_length=255, verbose_name='职位')),
                ('salaryMin',
                 models.DecimalField(default=0.00, max_digits=10, decimal_places=2, verbose_name='薪资下限')),
                ('salaryMax',
                 models.DecimalField(default=0.00, max_digits=10, decimal_places=2, verbose_name='薪资上限')),
                ('salaryBonus', models.IntegerField(default=0, verbose_name='年终奖')),
                ('city', models.CharField(default='', max_length=255, verbose_name='城市', db_column='location')),
                ('exp', models.CharField(default='', max_length=255, verbose_name='经验', db_column='experience')),
                ('edu', models.CharField(default='', max_length=255, verbose_name='学历', db_column='education')),
                ('industry', models.CharField(default='', max_length=255, verbose_name='行业')),
                ('num', models.IntegerField(default='', verbose_name='招聘人数')),
                ('tags', models.CharField(default='', max_length=255, verbose_name='福利待遇', db_column='tagList')),
                ('type', models.CharField(default='', max_length=255, verbose_name='职位类型')),
                ('content', models.TextField(default='', verbose_name='职位描述')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joblist',
                                              to='myApp.company', verbose_name='公司')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='joblist',
                                            to='myApp.employer', verbose_name='经理')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('keyList', models.TextField(default='', verbose_name='关键词')),
                ('urgency', models.CharField(default='', max_length=255, verbose_name='紧急程度')),
                ('status', models.CharField(default='', max_length=255, verbose_name='状态')),
                ('delete', models.IntegerField(default=0, verbose_name='是否删除')),
            ],
            options={
                'db_table': 'joblist',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(default='', max_length=255, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
                ('realName', models.CharField(default='', max_length=255, verbose_name='真实姓名')),
                ('sex', models.CharField(default='', max_length=255, verbose_name='性别')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('mobile', models.CharField(default='', max_length=255, verbose_name='手机号')),
                ('email', models.CharField(default='', max_length=255, verbose_name='邮箱')),
                ('edu', models.CharField(default='', max_length=255, verbose_name='学历', db_column='education')),
                ('exp', models.CharField(default='', max_length=255, verbose_name='工作经验', db_column='experience')),
                ('city', models.CharField(default='', max_length=255, verbose_name='意向城市')),
                ('work', models.CharField(default='', max_length=255, verbose_name='意向岗位')),
                ('resume', models.FileField(default='', upload_to='resume', verbose_name='简历')),
                ('avatar', models.FileField(default='avatar/cat.jpg', upload_to='avatar', verbose_name='用户图像')),
                ('lastLoginTime', models.DateTimeField(auto_now_add=True, verbose_name='最后登录时间')),
                ('isOnline', models.IntegerField(default=0, verbose_name='是否在线')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(default='', max_length=255, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
                ('realName', models.CharField(default='', max_length=255, verbose_name='真实姓名')),
                ('sex', models.CharField(default='', max_length=255, verbose_name='性别')),
                ('position', models.CharField(default='', max_length=255, verbose_name='职位')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer',
                                              to='myApp.company', verbose_name='公司')),
                ('comName', models.CharField(default='', max_length=255, verbose_name='公司名称')),
                ('avatar', models.FileField(default='avatar/cat.jpg', upload_to='avatar', verbose_name='用户图像')),
                ('lastLoginTime', models.DateTimeField(auto_now_add=True, verbose_name='最后登录时间')),
                ('isOnline', models.IntegerField(default=0, verbose_name='是否在线')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'employer',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('count', models.IntegerField(default=1, verbose_name='点击次数')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.joblist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.joblist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
            ],
            options={
                'db_table': 'favorite',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(default='', max_length=255, verbose_name='公司名称')),
                ('size', models.CharField(default='', max_length=255, verbose_name='公司规模')),
                ('tag', models.CharField(default='', max_length=255, verbose_name='公司所属行业')),
                ('location', models.CharField(default='', max_length=255, verbose_name='公司详细地址')),
                ('logo', models.FileField(default='', upload_to='logo', verbose_name='公司logo')),
                ('content', models.TextField(default='', verbose_name='公司简介')),
                ('verification', models.FileField(default='', upload_to='verification', verbose_name='公司认证信息')),
                ('vfstatus', models.IntegerField(default=0, verbose_name='是否审核')),
                ('vfbool', models.IntegerField(default=0, verbose_name='是否通过认证')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('status', models.CharField(
                    choices=[('pending', '待处理'), ('viewed', '已查看'), ('interviewing', '面试中'),
                             ('finalPass', '面试通过'), ('hired', '已录用'), ('archived', '已淘汰')], default='pending',
                    max_length=20, verbose_name='状态')),
                ('applyTime', models.DateTimeField(auto_now_add=True, verbose_name='投递时间')),
                ('viewTime', models.DateTimeField(blank=True, null=True, verbose_name='查看时间')),
                ('interviewTime', models.DateTimeField(blank=True, null=True, verbose_name='面试时间')),
                ('feedback', models.TextField(default='', verbose_name='面试评价')),
                ('tags', models.CharField(default='', max_length=255, verbose_name='标签')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications',
                                          to='myApp.joblist', verbose_name='岗位')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications',
                                           to='myApp.user', verbose_name='求职者')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications',
                                               to='myApp.employer', verbose_name='招聘者'))
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='InterviewStage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('stage',
                 models.CharField(choices=[('initial', '初试'), ('retest', '复试'), ('final', '终试')], max_length=20,
                                  verbose_name='面试阶段')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='面试时间')),
                ('data', models.TextField(default='', help_text='面试官、地点、联系方式等', verbose_name='面试安排详情')),
                ('comment', models.TextField(default='', verbose_name='面试评价')),
                ('passed', models.IntegerField(default='', verbose_name='是否通过')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages',
                                                  to='myApp.application', verbose_name='application'))
            ],
            options={
                'db_table': 'interview',
                'ordering': ['createTime'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(blank=True, max_length=255, null=True, verbose_name='标识符')),
                ('senderType', models.IntegerField(default=1, verbose_name='发送方')),
                ('content', models.TextField(default='', verbose_name='消息内容')),
                ('type', models.CharField(default='text', max_length=255, verbose_name='消息类型')),
                ('fileUrl', models.CharField(blank=True, default='', max_length=255, verbose_name='url')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('isRead', models.IntegerField(default=0, verbose_name='是否已读')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           related_name='messages', to='myApp.user', verbose_name='求职者')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               related_name='messages', to='myApp.employer', verbose_name='招聘者')),
            ],
            options={
                'db_table': 'message',
                'ordering': ['-createTime'],
            },
        ),
    ]
