# Generated by Django 5.2.8 on 2026-05-07 08:48

import django.db.models.deletion
import myApp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="tag",
            field=models.CharField(default="", max_length=255, verbose_name="公司标签"),
        ),
        migrations.AlterField(
            model_name="employer",
            name="avatar",
            field=models.FileField(
                default="avatar/cat.jpg",
                upload_to=myApp.models.avatar_upload_path,
                verbose_name="用户图像",
            ),
        ),
        migrations.AlterField(
            model_name="joblist",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="职位名称"),
        ),
        migrations.AlterField(
            model_name="joblist",
            name="num",
            field=models.IntegerField(default=0, verbose_name="招聘人数"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.FileField(
                default="avatar/cat.jpg",
                upload_to=myApp.models.avatar_upload_path,
                verbose_name="用户图像",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="resume",
            field=models.FileField(
                default="", upload_to=myApp.models.resume_upload_path, verbose_name="简历"
            ),
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="行业代码"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="行业名称")),
                ("level", models.IntegerField(default=0, verbose_name="层级")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="myApp.industry",
                        verbose_name="父级行业",
                    ),
                ),
            ],
            options={
                "verbose_name": "行业分类",
                "verbose_name_plural": "行业分类",
                "ordering": ["code"],
            },
        ),
    ]
